#!/usr/bin/env bash
# intstall nginx and configure

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
sh -c "echo 'Hello World!' > /var/www/html/index.html"
service nginx start
