#!/usr/bin/env bash
# Check if the password argument is provided
if [ -z "$1" ]; 
then
    exit
fi

# Get the current date for the backup file name
backup_date=$(date +%d-%m-%Y)

# MySQL root password
mysql_password="$1"

# MySQL dump command
mysql_dump_cmd="mysqldump -u root -p${mysql_password} --all-databases > backup.sql"

# Generate the MySQL dump
eval "$mysql_dump_cmd"

# Compress the MySQL dump
backup_file="${backup_date}.tar.gz"
tar -czvf "$backup_file" backup.sql
